# Generated by Django 5.1.3 on 2024-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_administrativo', models.BooleanField(default=False)),
            ],
        ),
    ]
