# Generated by Django 4.2.1 on 2024-11-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libromayor', '0002_delete_catalogocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('tipoDeCuenta', models.CharField(max_length=50)),
                ('nombreDeCuenta', models.CharField(max_length=100)),
                ('debe', models.FloatField(blank=True, null=True)),
                ('haber', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
