# Generated by Django 4.2.1 on 2024-11-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libromayor', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoCuenta',
        ),
    ]
