# Generated by Django 5.1.3 on 2024-11-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libromayor', '0008_catalogocuenta_saldo_acreedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogocuenta',
            name='saldo_acreedor',
        ),
        migrations.RemoveField(
            model_name='catalogocuenta',
            name='saldo_deudor',
        ),
    ]
